#!/usr/bin/env sh
load_env () { [ -f .env ] && for a in $1; do
	export $a="$(cat .env | grep $a= | sed -e "s/.*=//g")"; done; }

load_env "env npm_config_registry dev_on_host" # see terminal/lib.sh

if [ "$env" = "dev" ]; then
	if [ "$dev_on_host" = "true" ]; then
		docker-compose -p "$docker_prefix" -f docker-compose.dev-proxy.yml up --build -d
		(cd .. && npm run dev)
	else
		docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
		docker-compose exec app npm run dev
	fi
elif [ "$env" = "prod" ]; then
	docker-compose -f docker-compose.yml up -d
else echo "unknown env '$env', check .env"; fi
